apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-conf
data:
    nginx.conf: server{  listen 80; location / { proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $remote_addr;  proxy_set_header Host $host; proxy_pass http://go-hpa-service:80; } }
