apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-hpa

spec:
  selector:
    matchLabels:
      app: go-hpa
  
  template:
    metadata:
      labels:
        app: go-hpa
    spec:
      containers:
        - name: go-hpa
          image: despossivel/go-hpa
          ports:
          - containerPort: 80
          resources:
            requests:
                memory: "100Mi"
                cpu: "50m"
            limits:
                cpu: "100m"
                memory: "200Mi"