apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
	name: go-hpa-hpa
spec:
	maxReplicas: 1
	minReplicas: 6
	scaleTargetRef:
		apiVersion: extensions/v1beta1
		kind: Deployment
		name: go-hpa
    targetCPUUtilizationPercentage: 15
    resources:
        requests:
            memory: "100Mi"
            cpu: "50m"
        limits:
            cpu: "100m"
            memory: "200Mi"